### ISSUE TITLE
Android: Manifest merger failed

### ISSUE THREAD

**Issue by tgangso** [ionic-team/ionic-native#3335] opened 2020-03-02 16:24 UTC
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Not sure if capacitor or issue with this plugin or ionic native, but any help would be appreciated.

Following this guide: https://ionicframework.com/docs/native/purchases

After adding the plugin, i get this error in android studio:

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:5:5-43:19 to override.

**Expected behavior:**
Android build building with this plugin added.

**Steps to reproduce:**
Create a new project with capacitor and ionic-native, install the plugins in this guide:
https://ionicframework.com/docs/native/purchases

Add android as platform, then try to build the android project

**Comment by vegaro** [comment] 2020-03-02 22:06
Will follow up here https://github.com/RevenueCat/cordova-plugin-purchases/issues/30

**Comment by jcesarmobile** [comment] 2020-03-11 14:20
closing since the problem is not on ionic-native

**Closed by jcesarmobile** 2020-03-11 14:20 UTC
