### ISSUE TITLE
@ionic-native/keyboard use deprecated plugin

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic-native#2739] opened 2018-09-25 10:52 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The keyboard plugin use the deprecated https://github.com/ionic-team/ionic-plugin-keyboard instead of the new version https://github.com/ionic-team/cordova-plugin-ionic-keyboard

**Expected behavior:**
The keyboard plugin works with https://github.com/ionic-team/cordova-plugin-ionic-keyboard.

**Steps to reproduce:**
N/A

**Other information:**
See https://github.com/ionic-team/ionic-plugin-keyboard/issues/305#issuecomment-364198332 for migration path

**Comment by kensodemann** [comment] 2018-09-25 11:38
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #2306. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.

#2306 is in process at this time.

Thank you for using Ionic

**Closed by kensodemann** 2018-09-25 11:38 UTC
